export const permissionList = [
  "dashboard-view",
  "user-view",
  "user-get-by-id",
  "user-create",
  "user-edit",
  "user-delete",
  "notification-view",
  "notification-get-by-id",
  "notification-create",
  "notification-edit",
  "notification-delete",
  "activityLog-view",
  "role-view",
  "role-get-by-id",
  "role-create",
  "role-edit",
  "role-delete",
  "permission-view",
  "permission-get-by-id",
  "permission-create",
  "permission-edit",
  "permission-delete",
  "permission-createCrudPermissions",
  "roleHasPermission-view",
  "roleHasPermission-get_data_by_role_id",
  "roleHasPermission-sync",
  "roleHasPermission-give",
  "panel-view",
  "panel-get-by-id",
  "panel-create",
  "panel-edit",
  "panel-delete",
  "membershipType-view",
  "membershipType-get-by-id",
  "membershipType-create",
  "membershipType-edit",
  "membershipType-delete",
  "voterRegistration-view",
  "voterRegistration-get-by-id",
  "voterRegistration-create",
  "voterRegistration-edit",
  "voterRegistration-delete",
  "voterRegistration-status-view",
  "voterRegistration-status-update",
  "voterRegistration-approve",
  "voterRegistration-dispute",
  "voterRegistration-mark-pending",
  "voterRegistration-payment-view",
  "voterRegistration-payment-toggle",
  "voterRegistration-mark-paid",
  "voterRegistration-mark-unpaid",
  "voterRegistration-age-status-view",
  "voterRegistration-mark-voted",
  "voterRegistration-voted-status-toggle",
  "voterRegistration-photo-upload",
  "voterRegistration-photo-delete",
  "voterRegistration-export",
  "voterRegistration-import",
  "voterRegistration-filter",
] as const;

export const roleList = [
  "Super Admin",
  "Panel Admin",
  "Election Commission",
  "Voter",
  "Poll Officer",
] as const;

export type PermissionEnum = (typeof permissionList)[number];
export type RoleEnum = (typeof roleList)[number];
